[package]
name = "tique"
version = "0.1.0"
authors = ["Caio Romão <contact@caio.co>"]
edition = "2018"

[dependencies]
tique_derive = { path = "../tique_derive" }
tantivy = "0.11"
serde = { version = "1", features = ["derive"] }
byteorder = "1.3"
nom = "5"

[dev-dependencies]
zerocopy = "0.2"
rand = "0.7"
