[package]
name = "cantine"
version = "0.1.0"
authors = ["Caio Romão <hello@caio.co>"]
edition = "2018"

[dependencies]
tantivy = "0.10"
actix-web = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"
memmap = "0.7"
byteorder = "1.3.2"
fs2 = "0.4.3"
nom = "5"
bincode = "1"
