[package]
name = "tique"
version = "0.1.0"
authors = ["Caio Romão <contact@caio.co>"]
edition = "2018"

[features]
default = []
unstable = ["nom"]

[dependencies]
tantivy = "0.11"

nom = { version = "5", optional = true }

[dev-dependencies]
zerocopy = "0.2"
rand = "0.7"
