[package]
name = "cantine"
version = "0.1.0"
authors = ["Caio Romão <contact@caio.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1"
byteorder = "1.3"
memmap = "0.7"
serde = { version = "1", features = ["derive"] }
tempfile = "3"
zerocopy = "0.2"
